- CLIENT/src/components/Login/Login.jsx
- CLIENT/src/components/LoginForm/LoginForm.jsx
- CLIENT/src/redux/action-types/index.js
- CLIENT/src/redux/actions/index.js
modelo de formulario para iniciar sesión, dependiendo de las los nombres y las funcionalidades se va a modificar.
> Login form

- CLIENT/src/App.js
- CLIENT/src/components/CreateUser/CreateUser.jsx
Arregle una sintaxis que se veía mal en el form de registro, y redirigí el formulario al botón de la landing.
> arreglo de sintaxis-redireccion de form

- CLIENT/src/components/Card/Card.jsx
- CLIENT/src/components/Footer/Footer.css
- CLIENT/src/components/Footer/Footer.jsx
- CLIENT/src/components/Home/Home.jsx
- CLIENT/src/components/LandingHome/LandingHome.jsx
Arregle el map de home para que se renderice las imágenes, quite de la landing momentáneamente lo que impedía apretar el botón de ingreso
> arreglos para renderizar imágenes al home

- CLIENT/package-lock.json
- CLIENT/package.json
- CLIENT/src/components/Home/Home.jsx
- CLIENT/src/components/ProductDetail/ProductDetail.jsx
- CLIENT/src/redux/actions/index.js
- CLIENT/src/redux/store/index.js
-Se implementa accion de getDetail para que se observen los detalles del producto en la url id
-Se instala dependicia redux-logger que permite ver que acciones del reducer se estan ejecutando en la consola del navegador
> agregar logger en store de redux e implementar action get detail

- CLIENT/src/components/ProductDetail/ProductDetail.css
- CLIENT/src/components/ProductDetail/ProductDetail.jsx
Agregue el primer estilo al detalle, para que tenga una estructura base, en el próximo Sprint se perfecciona
> primer estilo al Detail

- CLIENT/src/components/Filters/Filters.jsx
- CLIENT/src/redux/actions/index.js
- Se agrega la opcion de filtrado por color.
> Agregado de filtro por color

- CLIENT/public/index.html
- CLIENT/src/App.js
- CLIENT/src/components/Home/Home.css
- CLIENT/src/components/Home/Home.jsx
- CLIENT/src/redux/actions/index.js
- Se implementa React Context para la perduracion de los filtrados y busqueda por nombre a traves de la navegacion por la pagina.
> Implementacion de React Context

- CLIENT/src/components/LoginForm/LoginForm.jsx
- Se hace un fix temporal de crear una funcion handleLogin para manejar la autenticacion de credenciales con el servidor en el componente de formulario de login
> temporal fix manejar autenticacion login

- CLIENT/src/context/AppContext.jsx
- Se agrega la carpeta context.
> Correction bug AppContext

- CLIENT/package-lock.json
- CLIENT/package.json
- CLIENT/src/components/CartItem/CartItem.css
- CLIENT/src/components/CartItem/CartItem.jsx
- CLIENT/src/components/Home/Home.jsx
- CLIENT/src/components/Orders/Orders.css
- CLIENT/src/components/Orders/Orders.jsx
- CLIENT/src/redux/actions/index.js
- CLIENT/src/redux/reducer/index.js
Volví a hacer el componente de ordenamiento por alfabeto, el que estaba estaba mal, renderice la imagen del producto en el carrito y lo centralicé un poco
> correcion-componente-order/agregar-detalles-cart

- CLIENT/src/components/Home/Home.jsx
- CLIENT/src/context/AppContext.jsx
- CLIENT/src/redux/actions/index.js
- Se corrige el paginado trabajandolo desde el back.
> Paginated Correction

- CLIENT/src/components/Home/Home.jsx
- CLIENT/src/context/AppContext.jsx
- CLIENT/src/redux/actions/index.js
- Se agrega ordenamiento por precio y nombre de forma asc o desc desde el back
> Agregado de ordenamientos

- CLIENT/src/components/NavBar/NavBar.jsx
- CLIENT/src/components/Profile/Profile.jsx
- CLIENT/src/utils/getSession.js
- Se conecta el componente profile con la ruta del backend para solicitar informacion mediante token
- Se modulariza funcion para obtener token del navegador queda en el archivo /utils/getSession.js
> conexion componente profile con el backend

- CLIENT/package-lock.json
- CLIENT/package.json
- CLIENT/src/index.js
- CLIENT/src/redux/actions/index.js
> configuracion de rutas

- CLIENT/src/components/Home/Home.jsx
- Se agregan mas opciones a la hora de filtrar por color en el componente Home.
> Add Colors Options

- CLIENT/src/components/ProductDetail/ProductDetail.jsx
- Se agregan los filtros por color y talle para poder filtrar el stock
> Agregado de filtros para filtrar por stock

- CLIENT/src/components/ProductDetail/ProductDetail.jsx
- CLIENT/src/redux/actions/index.js
- CLIENT/src/redux/reducer/index.js
Conectado addToFavorites al back, copiando metodo del shoppingCart.
No puedo chequear funcionamiento ya que no me funciona bien el back.
> faovrites connect to back

- CLIENT/src/components/ProductDetail/ProductDetail.jsx
- Se corrige el filtrado del stock para que cuando no haya mas de una opcion directamente se muestre esa opcion unica.
> Filters stock Correction

- CLIENT/src/components/ProductDetail/ProductDetail.jsx
- CLIENT/src/components/ProductDetail/ProductDetail.module.css
- CLIENT/src/context/AppContext.jsx
- Se agrega un poco de estilo y corrige algunas cosas en el componente ProductDetail.
> Correccion de estilo al componente ProductDetail

- CLIENT/src/App.js
- CLIENT/src/components/NavBar/NavBar.jsx
botón para acceder al componente de estadísticas, le faltaran estilos
> feat(src/components) add button to access the stadistics component

- CLIENT/src/redux/reducer/index.js
- Se corrige el mensaje de no existencia de productos cuando no machea con ningun filtro y se pasa al español el mensaje de loading.
> Correccion de mensaje de no existencia de productos y loading

- CLIENT/src/components/NavBar/NavBar.jsx
Se agrego link para redireccionar al Home, útil para cuando nos encontramos en pantalla de favoritos o carrito.
Se volvió a hacer que al cerrar sesión cargue Home y no Landing.
Se limpió código en NavBar.
> Cambios NavBar

- CLIENT/src/App.js
- CLIENT/src/components/LoginForm/LoginForm.jsx
- CLIENT/src/components/NavBar/NavBar.jsx
- CLIENT/src/components/ProtectedRoute/ProtectedRoute.jsx
Persiste el estado desde LOCALSTORAGE el cual se limpia cuando se cierra sesion
> correciones de rutas y hacer que persista el estado

- CLIENT/package-lock.json
- CLIENT/package.json
- CLIENT/src/App.js
- CLIENT/src/components/Card/Card.jsx
- CLIENT/src/components/CartItem/CartItem.jsx
- CLIENT/src/components/CreateStore/CreateStore.jsx
- CLIENT/src/components/FavItem/FavItem.jsx
- CLIENT/src/components/Favorites/Favorites.jsx
- CLIENT/src/components/Home/Home.jsx
- CLIENT/src/components/LoginForm/LoginForm.jsx
- CLIENT/src/components/NavBar/NavBar.module.css
- CLIENT/src/redux/reducer/index.js
Se limpio codigo codigo innecesario.
Se arregló un bug que cuando deslogueaba no podia volver a loguearse.
> limpieza de codigo

- CLIENT/package.json
- CLIENT/src/components/SellsGraphic/SellsGraphic.jsx
- CLIENT/src/components/Stadistics/Stadistics.jsx
el gráfico ya está funcionando, la lógica está en el componente de estadísticas , faltaría conectarlo con el back o pasar esa lógica al back
> Stadistic graphic

- CLIENT/src/components/ProductDetail/ProductDetail.jsx
el ternario provocaba que se rompiera el front, lo cambié por condicional
> error corregido

- CLIENT/package-lock.json
- CLIENT/package.json
- CLIENT/src/components/LoginForm/LoginForm.jsx
- CLIENT/src/components/NavBar/NavBar.jsx
- CLIENT/src/sessionUtils/jwtSession.js
Reverts Carsefer/PF-Clothes-Client#107
> Revert "Implementacion login google y username/password"

- CLIENT/src/components/CartItem/CartItem.jsx
- CLIENT/src/components/NavBar/NavBar.jsx
- CLIENT/src/components/ProductDetail/ProductDetail.jsx
- CLIENT/src/components/ShoppingCart/ShoppingCart.jsx
Cambiado el boton de carrito para que envie las variantes y agregado el color y size a las cartas de la lista del carrito
> Cart Itemschange

- CLIENT/src/components/Stadistics/Stadistics.jsx
el componente de estadísticas ahora muestra ordenadamente los 5 productos más vendidos
> Stadistics component

- CLIENT/src/App.js
- CLIENT/src/components/EditUser/EditUser.jsx
- CLIENT/src/components/EditUser/EditUser.module.css
- CLIENT/src/components/NavBar/NavBar.jsx
- CLIENT/src/components/Profile/Profile.jsx
Creacion de componente para editar usuario
> creacion-componente-editar-usuario

- CLIENT/src/App.js
- CLIENT/src/components/CreateUser/CreateUser.jsx
- CLIENT/src/components/NotVerified/NotVerified.jsx
- CLIENT/src/components/NotVerified/NotVerified.module.css
- CLIENT/src/components/Verified/verified.jsx
Backend
-  Se crea nuevo campo verified en el model de profiles
-  Se crean rutas para manejar el proceso de verficacion de cuenta de usuario
Frontend
-  Se crea componente para verificacion de cuenta y para cuando falla la verificacion
Flujo Verificacion de cuenta
Se Crea el usuario con campo verificacion con valor false
Se envia el correo de verificacion
Se ingresa al link del mensaje de verificacion
- En caso de ser exitosa se modifica el campo verified en el modelo de profiles al valor true al momento de hacer click en el enlace y te redirecciona a la pagina principal del ecommerce
- En caso de fallar la verificacion te redirige a un enlace para reenviar el correo de confirmacion
> Proceso de verificacion de cuenta

- CLIENT/src/components/ProductDetail/ProductDetail.jsx
- Se implementra que el comprador solo pueda hacer reseñas a sus productos comprados.
> Comprador solo puede hacer reseñas a sus productos comprados

- CLIENT/src/components/ShoppingCart/ShoppingCart.jsx
- CLIENT/src/redux/actions/index.js
- Accion nueva para que a la hora de comprar los productos se envia mail a los vendedores.
> Envio de mail a vendedores cuando se compra

- CLIENT/src/components/ShoppingCart/ShoppingCart.jsx
- Se corrige la repeticion en el renderizado de dos o mas productos iguales, haciendo la multiplicacion correspondiente y se agrega el total a pagar.
> Correccion bugs del shoppingCart

- CLIENT/src/components/ProductDetail/ProductDetail.jsx
- Se corrigen los bugs del componente ProductDetail.
> Correccion bugs ProductDetail

- CLIENT/src/components/Profile/Profile.jsx
- Se corrige la lista de "mis compras" para que no muestre elementos repetidos y muestre la cantidad de repeticiones del mismo elemento.
> Correccion bugs "Mis compras"

- CLIENT/src/App.js
- CLIENT/src/components/CartItem/CartItem.jsx
- CLIENT/src/components/Favorites/Favorites.jsx
- CLIENT/src/components/LoginForm/LoginForm.jsx
- CLIENT/src/components/NavBar/NavBar.jsx
- CLIENT/src/components/ProductDetail/ProductDetail.jsx
- CLIENT/src/components/ShoppingCart/ShoppingCart.jsx
se agrega link al producto en el carrito para que vaya al detalle y se modifica boton de atras en detalle para que vuelva atras y no necesariamente al home. 
mejor UX
> pequeños cambios

- CLIENT/src/components/LoginForm/LoginForm.jsx
- CLIENT/src/redux/store/index.js
Backend
- Se configura rutas de login para no permitir ingreso sin verificacion de cuenta
Frontend
- Se configuran mensajes para solicitar verificacion antes de permitir ingreso en la session de usuario
Flujo
- crear cuenta usuario/password
- cuenta usuario/password no verificado
- cuenta usuario/password credenciales incorrectas
- cuenta google no verificada
> Flujo de verificacion y login

- CLIENT/src/components/LoginForm/LoginForm.jsx
- se arregla un bracket que quedo mal ubicado en login que genera loop de cargar la pagina
> Fix bracket en funcion mal ubicado

- CLIENT/src/App.js
- CLIENT/src/components/NotFound/NotFound.jsx
- Componente que redirecciona a la pagina principal en caso de tratar de ingresar a una url no existente
> redireccion de url no existente

- CLIENT/src/components/CreateUser/CreateUser.jsx
- CLIENT/src/components/LoginForm/LoginForm.jsx
- CLIENT/src/components/SellingCard/SellingCard.jsx
Se agrega botones de volver a inicio en logIn y createUser
> Back buttons

- CLIENT/src/redux/actions/index.js
cambie la ruta que trae las ventas a la que solo trae las ventas del usuario
> feat(src/redux/actions) ruta correjida en getSellsHistoryEstadistics

- CLIENT/src/components/EditUser/EditUser.jsx
formulario para editar usuario controlado
> feat(src/components/EditUser) controlled Form

- CLIENT/src/components/Home/Home.jsx
Backend
- Se procede a modificar forma de pasar el token de session para login con google, ahora se pasar mediante un parametro de busqueda de la url que se llama gtoken
Frontend
- Se modifica componente Home para que almacene token de session de google directamente de la url al local storage
> fix google login for heroku

- CLIENT/src/redux/actions/index.js
- Ruta para las estadisticas arreglada de users a user
> fix estadistics
